### ISSUE TITLE
Can you upload App on Chrome Web Store?

### ISSUE THREAD

**Issue by devchae1** [AlyoshaVasilieva/luminous-ttv#3]
Currently, Twitch Korea has implemented a policy of limiting the video quality to 720p.
So there are a lot of people who want to use the servers and extensions you create.
For convenience, can you upload the app to the Chrome Web Store?

**Comment by AlyoshaVasilieva** [comment]
Unfortunately the extension can't be published on the Chrome Web Store due to Google policies. It's a manifest v2 extension, which they [stopped accepting in June 2022](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/). I think it's technically possible to make it a v3 extension, but as far as I know I'd have to remove its configurability and the ability for it to fail-safe if my server is down.
