### ISSUE TITLE
does running this allow other Hola users to use your internet connection?

### ISSUE THREAD

**Issue by garbb** [AlyoshaVasilieva/luminous-ttv#7]
I was reading about the Hola vpn service and on the [wikipedia](https://en.wikipedia.org/wiki/Hola_(VPN)) it says:

> Users of the free service share a portion of their idle upload bandwidth to be used for serving cached data to other users

Does this mean that when you are running this server that other Hola users are able to use your internet connection to make outgoing connections? I am not necessarily complaining about this, but I think that it is something that people would want to be aware of.

**Comment by AlyoshaVasilieva** [comment]
As noted in the readme:

>You will not be acting as a peer of the Hola network.

It uses reverse engineered information of how their network works, just enough to say "I am an Hola browser extension, give me credentials" and "give me some proxies". It doesn't implement any of their botnet stuff, and since the only requests this server makes go over TLS they can't see anything sensitive. (plus users can provide their own non-hola proxies if they're worried)
